<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\MedicalReport;
use Illuminate\Support\Facades\Auth;

class DoctorController extends Controller
{
    public function dashboard()
    {
        // Get all patients (users with role 'user')
        $patients = User::where('role', 'user')->with('profile')->get();
        
        // Get reports generated by this doctor
        $reports = MedicalReport::where('doctor_id', Auth::id())->with('patient')->get();

        return view('doctor.dashboard', compact('patients', 'reports'));
    }

    public function uploadReport(Request $request)
    {
        $request->validate([
            'patient_id' => 'required|exists:users,id',
            'title' => 'required|string|max:255',
            'diagnosis' => 'required|string',
            'report_file' => 'nullable|file|mimes:pdf,jpg,png|max:5120', // 5MB max
        ]);

        $path = null;
        if ($request->hasFile('report_file')) {
            $path = $request->file('report_file')->store('medical_reports', 'public');
        }

        MedicalReport::create([
            'doctor_id' => Auth::id(),
            'patient_id' => $request->patient_id,
            'title' => $request->title,
            'diagnosis' => $request->diagnosis,
            'file_path' => $path,
        ]);

        return redirect()->back()->with('status', 'Report uploaded successfully.');
    }

    public function getDirectory()
    {
        // Get all users with the 'doctor' role
        $doctors = User::where('role', 'doctor')->with('profile')->get()->map(function ($doc) {
            // Simulated online status (randomized for prototype demonstration)
            $isOnline = rand(0, 1) == 1;
            $specialties = ['General Physician', 'Cardiologist', 'Neurologist', 'Pediatrician', 'Orthopedic Surgeon'];
            
            return [
                'id' => $doc->id,
                'name' => 'Dr. ' . $doc->name,
                'email' => $doc->email,
                'specialty' => $specialties[array_rand($specialties)], // Assign a random specialty if not in profile
                'isOnline' => $isOnline,
                'lastSeen' => $isOnline ? 'Now' : now()->subHours(rand(1, 24))->diffForHumans(),
            ];
        });

        return response()->json($doctors);
    }

    public function sendEmergencyAlert(Request $request, $id)
    {
        $doctor = User::find($id);
        
        if (!$doctor) {
            return response()->json(['error' => 'Doctor not found'], 404);
        }

        // Simulate sending Email and SMS
        \Illuminate\Support\Facades\Log::info("EMERGENCY ALERT SENT: Email and SMS dispatched to Dr. {$doctor->name} ({$doctor->email}) regarding an urgent patient case.");

        return response()->json(['message' => 'Emergency Alert sent successfully via Email and SMS! The doctor will be notified immediately.']);
    }
}
